#!/usr/bin/env node
/*
 * Compiles every wiring/*.netlist.json subsystem file into api/wiring-data.js,
 * a single dependency-free ESM module the Vercel function imports.
 *
 * Each subsystem is one wiring/<name>.netlist.json with shape:
 *   { "_meta": { "subsystem": "...", ... }, "components": [...], "connections": [...] }
 *
 * Components are merged by id (first definition wins; a later differing
 * definition is reported as a conflict). Connections are concatenated.
 * Cross-subsystem edges are fine — an edge may reference a component defined in
 * another file, as long as that component is defined exactly once somewhere.
 *
 * Run:  node wiring/build-netlist.cjs
 */
const fs = require('fs');
const path = require('path');

const WIRING_DIR = path.join(__dirname);
const OUT = path.join(__dirname, '..', 'api', 'wiring-data.js');

const files = fs.readdirSync(WIRING_DIR).filter(f => f.endsWith('.netlist.json')).sort();
if (!files.length) { console.error('No *.netlist.json files found in', WIRING_DIR); process.exit(1); }

const components = new Map();
const connections = [];
const subsystems = [];
let conflicts = 0;

for (const file of files) {
  const data = JSON.parse(fs.readFileSync(path.join(WIRING_DIR, file), 'utf8'));
  const sub = (data._meta && data._meta.subsystem) || file.replace('.netlist.json', '');
  subsystems.push(sub);
  for (const c of data.components || []) {
    if (components.has(c.id)) {
      const prev = JSON.stringify(components.get(c.id));
      if (prev !== JSON.stringify(c)) {
        console.warn(`  ! conflict: component "${c.id}" redefined in ${file} (keeping first)`);
        conflicts++;
      }
      continue;
    }
    components.set(c.id, c);
  }
  for (const e of data.connections || []) connections.push(e);
  console.log(`  + ${file}: ${(data.components || []).length} components, ${(data.connections || []).length} connections`);
}

const compArr = [...components.values()];

// Validate: every connection endpoint must be a defined component.
const ids = new Set(components.keys());
const missing = new Set();
for (const e of connections) {
  if (!ids.has(e.from)) missing.add(e.from);
  if (!ids.has(e.to)) missing.add(e.to);
}
if (missing.size) {
  console.error('\nERROR: connections reference undefined components:', [...missing].join(', '));
  process.exit(1);
}

const banner = `// AUTO-GENERATED by wiring/build-netlist.cjs — do not edit by hand.
// Source of truth: wiring/*.netlist.json. Run \`node wiring/build-netlist.cjs\` to regenerate.
`;
const body = `export const NETLIST = {
  meta: {
    vessel: 'Tiger — Swan 48 Mk2, Hull 233',
    subsystems: ${JSON.stringify(subsystems)},
    voltage: 24,
  },
  components: ${JSON.stringify(compArr, null, 2)},
  connections: ${JSON.stringify(connections, null, 2)},
};
`;
fs.writeFileSync(OUT, banner + body);
console.log(`\nWrote ${path.relative(path.join(__dirname, '..'), OUT)}: ${compArr.length} components, ${connections.length} connections across ${subsystems.length} subsystems${conflicts ? `, ${conflicts} conflict(s)` : ''}.`);
